name: shapp
description: Shopping, the easier way.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12

  provider: ^4.3.2
  rxdart: ^0.24.1
  intl: ^0.16.1

  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.2
  firebase_analytics: ^6.2.0

  google_maps_flutter: ^1.0.2
  location: ^3.0.2

  share: ^0.6.5
  dots_indicator: ^1.2.0
  image_picker: ^0.6.7
  intl_phone_number_input: ^0.5.2+2
  code_input: ^1.0.3
  devicelocale: ^0.3.3

  stripe_payment: ^1.0.8

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/map_style_dark
    - assets/map_style_light
    - assets/images/basket.png
    - assets/images/map.png
    - assets/images/supermarket_location.png
    - assets/images/shops/boutique.png
    - assets/images/shops/supermarket.png
    - assets/images/shops/cafe.png
    - assets/images/shops/restaurant.png
    - assets/images/shops/delicatessen.png
    - assets/images/shops/jewelry.png
    - assets/images/shops/electronics_shop.png
    - assets/images/shops/pet_shop.png
    - assets/images/shops/stationery.png
    - assets/images/shops/toy_store.png
    - assets/images/shops/repair_services.png
    - assets/images/shops/barber_shop.png
    - assets/images/shops/bookstore.png
    - assets/images/shops/furniture_store.png
    - assets/images/shops/sports_store.png
    - assets/images/shops/florist.png
    - assets/images/shops/fruit_shop.png
    - assets/images/shops/fish_shop.png
    - assets/images/products/basket.png
    - assets/images/products/drinks.png
    - assets/images/products/health.png
    - assets/images/products/cosmetics.png
    - assets/lang/en.json
    - assets/lang/nl.json
    - assets/images/AlbertHeijnXL.jpg

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel.ttf

