name: shapp
description: As quick as a click.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12

  provider: ^4.3.2
  rxdart: ^0.24.1
  intl: ^0.16.1

  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.2
  firebase_analytics: ^6.2.0
  firebase_storage: ^5.2.0
  firebase_remote_config: ^0.4.3
#  firebase_messaging: ^7.0.3
#  firebase_crashlytics: ^0.2.3

  google_maps_flutter: ^1.0.2
  location: ^3.0.2
  google_map_location_picker: ^4.1.2+1

  share: ^0.6.5
  dots_indicator: ^1.2.0
  image_picker: ^0.6.7
  intl_phone_number_input: ^0.5.2+2
  code_input: ^1.0.3
  devicelocale: ^0.3.3
  flutter_markdown: ^0.5.1

  stripe_payment: ^1.0.8


dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_native_splash: ^0.1.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/launcher/icon.png
  image_path_android: assets/launcher/icon.png

flutter_native_splash:
  image: assets/launcher/splash.png
  color: 333333
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/map_style_dark
    - assets/map_style_light
    - assets/images/basket.png
    - assets/images/map.png
    - assets/images/supermarket_location.png
    - assets/launcher/icon.png
    - assets/lang/en.json
    - assets/lang/nl.json
    - assets/policies/privacy_policy.md
    - assets/policies/general_conditions.md


  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel.ttf

